package de.pauleduardkoenig.dwds_cf.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.therazzerapp.milorazlib.ClipboardUtils;
import com.therazzerapp.milorazlib.swing.SwingUtils;
import com.therazzerapp.milorazlib.swing.components.JPopupMenuBasic;
import de.pauleduardkoenig.dwds_cf.Constants;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 * <description>
 *
 * @author Paul Eduard Koenig <rezzer101@googlemail.com>
 * @since 0.1.0
 */
public class GUIAbout extends JDialog{
    private JPanel mPanel;
    private JLabel icon;
    private JLabel creditsLabel;

    public GUIAbout(){
        $$$setupUI$$$();
        setTitle("About");
        setResizable(false);
        setModal(true);
        setContentPane(mPanel);
        setSize(430, 180);
        setLocationRelativeTo(null);
        setIconImage(Constants.PROGRAMM_ICON);
        SwingUtils.registerJTextComponentPopupMenu(new JPopupMenuBasic(), mPanel);

        icon.setIcon(new ImageIcon(ClassLoader.getSystemResource("dwds-sf_logo_150.png")));

        creditsLabel.setText("<html>DWDS-CF v. " + Constants.VERSION + "<br>Author Paul Eduard Koenig<br>Copyright &copy; 2024 - Paul Eduard Koenig<br>All Rights Reserved<br>pauleduardkoenig@gmail.com<br>Made for the institute of linguistics at<br>Frankfurt Goethe University.</html>");

        creditsLabel.addMouseListener(new MouseListener(){
            @Override
            public void mouseClicked(MouseEvent e){
                if (e.getClickCount() == 2 && !e.isConsumed()){
                    ClipboardUtils.copyTextToClipboard(creditsLabel.getText());
                }
            }

            @Override
            public void mousePressed(MouseEvent e){
                // empty
            }

            @Override
            public void mouseReleased(MouseEvent e){
                // empty
            }

            @Override
            public void mouseEntered(MouseEvent e){
                // empty
            }

            @Override
            public void mouseExited(MouseEvent e){
                // empty
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$(){
        mPanel = new JPanel();
        mPanel.setLayout(new GridLayoutManager(2, 4, new Insets(0, 0, 0, 0), -1, -1));
        final Spacer spacer1 = new Spacer();
        mPanel.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, 1, new Dimension(15, -1), new Dimension(15, -1), new Dimension(15, -1), 0, false));
        final Spacer spacer2 = new Spacer();
        mPanel.add(spacer2, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        icon = new JLabel();
        icon.setText("");
        mPanel.add(icon, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        creditsLabel = new JLabel();
        creditsLabel.setText("A");
        mPanel.add(creditsLabel, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("");
        mPanel.add(label1, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        mPanel.add(spacer3, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$(){
        return mPanel;
    }
}
